language: php
php:
  - 7.0

sudo: false
matrix:
  fast_finish: true

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/tester tests/ -c tests/php.ini --coverage coverage.xml --coverage-src src/

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

cache:
  directories:
    - $HOME/.composer/cache
