language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - hhvm

sudo: false
matrix:
  fast_finish: true

  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - if [[ $TRAVIS_PHP_VERSION = 'hhvm' ]]; then vendor/bin/tester tests/ -p hhvm -c tests/php.ini; fi
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then vendor/bin/tester tests/ -c tests/php.ini --coverage coverage.xml --coverage-src src/; fi

after_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi

cache:
  directories:
    - $HOME/.composer/cache
